spring:
  application:
    name: Digital-Wallet
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
      root: INFO
      com.digitalwallet.controller: DEBUG
      com.digitalwallet.service: DEBUG
      com.digitalwallet.repository: INFO
      com.digitalwallet.mapper: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
